name: Chainloop Metadata Collection and Attestation Process
on:
  workflow_call:
    inputs:
      chainloop_version:
        required: false
        type: string
      contract_revision:
        required: false
        type: string
    secrets:
      api_token:
        required: true
      signing_key:
        required: true
      signing_key_password:
        required: true
    
jobs:
  chainloop-attestation:
    name: Chainloop Attestation Process
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .chainloop.yml

      - uses: sigstore/cosign-installer@v3.1.1
  
      - name: Install Chainloop Labs Functions
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/chainloop-dev/labs/dev/tools/src/lib/chainloop.sh)" && install_chainloop_labs dev
    
      - name: Install Chainloop CLI
        run: |
          . ~/chainloop.sh && install_chainloop_cli_and_cosign

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Initialize Attestation
        run: . ~/chainloop.sh && chainloop_attestation_init

      - name: Add all artifacts, reports, and metadata to attestation.
        run: |
          script=`cat .chainloop.yml | yq eval '.attestation[] | "chainloop attestation add --name "  + .name + " --value " + .path + "; "'`
          eval $script
 
      - name: Chainloop Attestation Status
        run: |
          chainloop attestation status --full &> c8-status.txt
          cat c8-status.txt
 
      - name: Validate Collected Artifacts and Record Attestation
        if: ${{ success() }}
        run: |
          chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY &> c8-push.txt
          cat c8-push.txt
        env:
          CHAINLOOP_SIGNING_KEY: ${{ secrets.signing_key }}
          CHAINLOOP_SIGNING_PASSWORD: ${{ secrets.signing_key_password }}
  
      - name: Generate a summary report
        run: |  
          digest=`cat c8-push.txt| grep " Digest: " | awk -F\  '{print $3}'`
          echo -e "## Great job!\nYou are making SecOps and Compliance teams really happy. Keep up the good work!\n" >> $GITHUB_STEP_SUMMARY
          echo "**[Chainloop Trust Report](https://app.chainloop.dev/attestation/${digest})**" >> $GITHUB_STEP_SUMMARY 
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 
          cat c8-status.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 

      - name: Mark attestation as failed
        if: ${{ failure() }}
        run: |
          chainloop attestation reset
          ~/.chainloop.sh && chainloop_generate_github_summary_on_failure
          
      - name: Mark attestation as cancelled
        if: ${{ cancelled() }}
        run: |
          chainloop attestation reset --trigger cancellation

    env:
      CHAINLOOP_VERSION: ${{ inputs.chainloop_version }}
      CHAINLOOP_ROBOT_ACCOUNT: ${{ secrets.api_token }}
      CHAINLOOP_CONTRACT_REVISION: ${{ inputs.contract_revision }}
      
