name: Chainloop Attestation Process
on:
  workflow_call:
    inputs:
      chainloop_version:
        required: false
        type: string
      contract_revision:
        required: false
        type: string
    secrets:
      api_token:
        required: true
      signing_key:
        required: true
      signing_key_password:
        required: true
    
jobs:
  chainloop-attestation:
    name: Chainloop Attestation Process
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .chainloop.yml

      - name: Install Chainloop CLI, Labs and Cosign
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/chainloop-dev/labs/dev/tools/src/lib/chainloop.sh) ; install_chainloop_labs dev"
          . ~/chainloop.sh
          install_chainloop_cli_and_cosign

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Initialize Attestation
        run: . ~/chainloop.sh && chainloop_attestation_init && ls -las

      - name: logs
        run: . ~/chainloop.sh && chainloop_collect_logs_for_github_jobs
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Add all artifacts, reports, and metadata to attestation.
        run: . ~/chainloop.sh && chainloop_attestation_add_from_yaml
 
      - name: Chainloop Attestation Status
        run: . ~/chainloop.sh && chainloop_attestation_status
 
      - name: Validate Collected Artifacts and Record Attestation
        if: ${{ success() }}
        run: . ~/chainloop.sh && chainloop_attestation_push
        env:
          CHAINLOOP_SIGNING_KEY: ${{ secrets.signing_key }}
          CHAINLOOP_SIGNING_PASSWORD: ${{ secrets.signing_key_password }}
  
      - name: Generate a summary report
        run: . ~/chainloop.sh && chainloop_generate_github_summary

      - name: Mark attestation as failed
        if: ${{ failure() }}
        run: |
          chainloop attestation reset
          . ~/chainloop.sh && chainloop_generate_github_summary_on_failure
          
      - name: Mark attestation as cancelled
        if: ${{ cancelled() }}
        run: |
          chainloop attestation reset --trigger cancellation

    env:
      CHAINLOOP_VERSION: ${{ inputs.chainloop_version }}
      CHAINLOOP_ROBOT_ACCOUNT: ${{ secrets.api_token }}
      CHAINLOOP_CONTRACT_REVISION: ${{ inputs.contract_revision }}
      
